# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as 
# well as the filename.
# timezone =

# max length of 'slug' field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults to alembic/versions.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# the propagation of the 'stdout' attribute to the 'alembic.config.Config'
# object, if one is given.
# stdout_level = INFO

sqlalchemy.url = postgresql://postgres.yxtbkarphbstpmweirvh:sameer9155649575@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
